name: Build and Test

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp: [23, 24, 25]
        elixir: [1.14]
        include:
          - os: ubuntu-latest
            elixir: 1.14
            otp: 25
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache deps and build for mix
        uses: actions/cache@v2
        id: cache-mix
        with:
          path: |
            deps
            _build
          key: ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-${{ matrix.otp }}-
            ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-
            ${{ matrix.os }}-mix-
      - if: steps.cache-mix.outputs.cache-hit != 'true'
        run: mix do deps.get + deps.compile + dialyzer --plt
      - run: mix dialyzer --format github
      - run: mix compile

  test:
    name: Test (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp: [23, 24, 25]
        elixir: [1.14]
        include:
          - os: ubuntu-latest
            elixir: 1.14
            otp: 25
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache deps and build for mix
        uses: actions/cache@v2
        id: cache-mix
        with:
          path: |
            deps
            _build
          key: ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-${{ matrix.otp }}-
            ${{ matrix.os }}-mix-${{ env.MIX_ENV }}-
            ${{ matrix.os }}-mix-
      - run: mix format --check-formatted
      - if: steps.cache-mix.outputs.cache-hit != 'true'
        run: mix do deps.get + deps.compile
      - run: mix do compile + test
      - run: mix test --cover
